#!/usr/bin/env bash
# =============================================================================
# generate-env.sh — Generate .env file dengan secret values
#
# Usage:
#   scripts/generate-env.sh                              # interactive (asks for DOMAIN, email)
#   scripts/generate-env.sh --domain=insuretrack.id      # non-interactive
#   scripts/generate-env.sh > .env                       # langsung tulis ke .env
#   scripts/generate-env.sh --slip=20.189.121.230        # generate untuk sslip.io dev
#
# Output: lengkap .env format, ready to copy-paste per line ke Dokploy
# Secrets tab, atau save ke .env file.
#
# Yang di-generate otomatis: POSTGRES_PASSWORD, JWT_SECRET,
# PAYMENT_WEBHOOK_SECRET. Yang harus diisi manual: RESEND_API_KEY
# (dari Resend dashboard), DOMAIN, dan opsional ACME_EMAIL.
# Plus: COOKIE_DOMAIN & COOKIE_SECURE (lihat block "Session cookies"
# di bawah) — perlu di-set di production untuk cookie share
# antar subdomain + HTTPS-only.
# =============================================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# Parse args
DOMAIN=""
SLIP_IP=""
RESEND_API_KEY="re_replace_with_resend_dashboard_key"
RESEND_FROM_EMAIL=""
ACME_EMAIL=""
BACKUP_OFFSITE_TARGET=""

for arg in "$@"; do
    case "$arg" in
        --domain=*)
            DOMAIN="${arg#*=}"
            ;;
        --slip=*)
            SLIP_IP="${arg#*=}"
            DOMAIN="${SLIP_IP//./-}.sslip.io"
            ;;
        --resend-key=*)
            RESEND_API_KEY="${arg#*=}"
            ;;
        --from-email=*)
            RESEND_FROM_EMAIL="${arg#*=}"
            ;;
        --acme-email=*)
            ACME_EMAIL="${arg#*=}"
            ;;
        --offsite=*)
            BACKUP_OFFSITE_TARGET="${arg#*=}"
            ;;
        -h|--help)
            sed -n '2,20p' "$0"
            exit 0
            ;;
    esac
done

# Interactive prompt kalau belum ada
if [[ -z "$DOMAIN" ]]; then
    echo "Domain config:" >&2
    echo "  1) Real domain (production) — mis. insuretrack.id" >&2
    echo "  2) sslip.io (dev/demo) — mis. 20.189.121.230" >&2
    read -r -p "Pilih [1/2]: " DOMAIN_CHOICE
    case "$DOMAIN_CHOICE" in
        2)
            read -r -p "Public IP VPS: " SLIP_IP
            DOMAIN="${SLIP_IP//./-}.sslip.io"
            ;;
        *)
            read -r -p "Domain (mis. insuretrack.id): " DOMAIN
            ;;
    esac
fi

if [[ -z "$RESEND_FROM_EMAIL" ]]; then
    read -r -p "RESEND_FROM_EMAIL (mis. noreply@$DOMAIN) [default: noreply@$DOMAIN]: " INPUT
    RESEND_FROM_EMAIL="${INPUT:-noreply@$DOMAIN}"
fi

# Generate secrets
POSTGRES_PASSWORD=$(openssl rand -hex 24)
JWT_SECRET=$(openssl rand -hex 64)
PAYMENT_WEBHOOK_SECRET=$(openssl rand -hex 32)

# Output .env format
cat <<EOF
# =============================================================================
# InsureTrack — generated by scripts/generate-env.sh at $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# DO NOT COMMIT THIS FILE — .env is in .gitignore
# =============================================================================

# ---- Domain (Traefik routing) --------------------------------------------
DOMAIN=$DOMAIN
${ACME_EMAIL:+ACME_EMAIL=$ACME_EMAIL}

# ---- Replicas ------------------------------------------------------------
REPLICAS=2

# ---- Public URLs --------------------------------------------------------
NEXT_PUBLIC_API_URL=https://api.\${DOMAIN}
APP_BASE_URL=https://portal.\${DOMAIN}
MEDIA_BASE_URL=https://api.\${DOMAIN}

# ---- Database ------------------------------------------------------------
POSTGRES_USER=insurance_admin
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=digital_insurance
DATABASE_URL=postgres://insurance_admin:$POSTGRES_PASSWORD@db:5432/digital_insurance

# ---- Auth & secrets ------------------------------------------------------
JWT_SECRET=$JWT_SECRET
PAYMENT_WEBHOOK_SECRET=$PAYMENT_WEBHOOK_SECRET

# ---- Session cookies (httpOnly, double-submit CSRF) ----------------------
# Default value cukup untuk dev. Production:
#   COOKIE_DOMAIN=.${DOMAIN}     (leading dot — share cookie di *.DOMAIN)
#   COOKIE_SECURE=true            (HTTPS only)
#   CORS_ALLOWED_ORIGINS=https://portal.${DOMAIN},https://admin.${DOMAIN}
SESSION_COOKIE_NAME=insuretrack_session
CSRF_COOKIE_NAME=insuretrack_csrf
COOKIE_DOMAIN=
COOKIE_SECURE=false
CORS_ALLOWED_ORIGINS=

# ---- Storage backend -----------------------------------------------------
STORAGE_BACKEND=local
UPLOAD_DIR=/var/uploads

# ---- Email (Resend) ------------------------------------------------------
RESEND_API_KEY=$RESEND_API_KEY
RESEND_FROM_EMAIL=$RESEND_FROM_EMAIL

# ---- DB Backup -----------------------------------------------------------
BACKUP_CRON_SCHEDULE=@daily
BACKUP_KEEP_DAYS=7
BACKUP_KEEP_WEEKS=4
BACKUP_KEEP_MONTHS=6
BACKUP_KEEP_YEARS=1
${BACKUP_OFFSITE_TARGET:+BACKUP_OFFSITE_TARGET=$BACKUP_OFFSITE_TARGET}

# ---- Backend runtime -----------------------------------------------------
PORT=8080
RUST_LOG=info,insuretrack_backend=debug
EOF

# Tulis ke .env kalau di-redirect, atau tampilkan di stdout dengan instruksi
if [[ -t 1 ]]; then
    # Stdout adalah terminal (bukan redirect)
    cat <<'INSTRUCTIONS' >&2

# =============================================================================
# NEXT STEPS:
# =============================================================================
# 1. Fill in RESEND_API_KEY from https://resend.com/api-keys
#    (replace 're_replace_with_resend_dashboard_key' above)
# 2. Choose ONE of these to deploy:
#
#    A) Save to .env file (for local dev or Dokploy 'Import .env'):
#         scripts/generate-env.sh --domain=$DOMAIN > .env
#       Then edit .env to fill RESEND_API_KEY.
#
#    B) Copy-paste to Dokploy Secrets tab:
#         Di Dokploy → service → tab Environment → section Secrets
#         Copy line per line dari output di atas.
#
#    C) For sslip.io dev: LE cert will be self-signed (browser warning).
#       Set traefik labels tls=false atau proceed anyway.
# =============================================================================
INSTRUCTIONS
fi
